// Import the createSlice function from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the user slice
const initialState = {
    user: null, // Initial state for the logged-in user, initially set to null
};

// Create a slice for user-related state and actions
const userSlice = createSlice({
    name: 'user', // Name of the slice
    initialState, // Initial state for the slice
    reducers: {
        // Reducer to handle user login
        login: (state, action) => {
            state.user = action.payload; // Set the user object on login with the payload from the action
        },
        // Reducer to handle user logout
        logout: (state) => {
            state.user = null; // Clear the user object on logout
        },
    },
});

// Export the actions generated by createSlice
export const { login, logout } = userSlice.actions;

// Export the reducer to be used in the store
export default userSlice.reducer;
